name: Blog Automation WorkFlow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Node.js script
      run: node index.js
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        HASHNODE_KEY: ${{ secrets.HASHNODE_KEY }}
        PUBLICATION_ID: ${{ secrets.PUBLICATION_ID }}
        MEDIUM_KEY: ${{ secrets.MEDIUM_KEY }}
        MEDIUM_ID: ${{ secrets.MEDIUM_ID }}
        X_APP_KEY: ${{ secrets.X_APP_KEY }}
        X_APP_SECRET: ${{ secrets.X_APP_SECRET }}
        X_APP_ACCESS_TOKEN: ${{ secrets.X_APP_ACCESS_TOKEN }}
        X_APP_ACCESS_SECRET: ${{ secrets.X_APP_ACCESS_SECRET }}
