name: Blog Automation WorkFlow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Node.js script
      run: node index.js
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        HASHNODE_KEY: ${{ secrets.HASHNODE_KEY }}
        PUBLICATION_ID: ${{ secrets.PUBLICATION_ID }}
